#ifdef SPANISH
	#define STR0001 "Monitoreo de Fe-SEFAZ"
	#define STR0002 "Rango"
	#define STR0003 "Tiempo"
	#define STR0004 "Buscar"
	#define STR0005 "Wiz.Config."
	#define STR0006 "Parametros"
	#define STR0007 "Estatus SEFAZ"
	#define STR0008 "Transmision"
	#define STR0009 "Monitor"
	#define STR0010 "Serie da nota fiscal"
	#define STR0011 "Factura inicial"
	#define STR0012 "Factura final"
	#define STR0013 "Esta rotina tem como objetivo auxilia-lo na transmissão da nota fiscal eletrônica para o serviço Totvs Services SPED. "
	#define STR0014 "En este momento, Totvs Services SPED esta operando con la siguiente configuracion: "
	#define STR0015 "Entorno: "
	#define STR0016 "Modalidad de emision: "
	#define STR0017 "Versão do layout: "
	#define STR0018 "Assistente de transmissão da nota fiscal eletrônica"
	#define STR0019 "Atencion"
	#define STR0020 "Siga atentamente los pasos para configurar la factura electronica."
	#define STR0021 "¡Ejecute el modulo de configuracion del servicio, antes de utilizar esta opcion!"
	#define STR0022 "Preparando factura: "
	#define STR0023 "Transmitiendo XML de la factura: "
	#define STR0024 "Las siguientes factura fueron rechazadas, verifique la rutina 'Monitor' para saber los motivos."
	#define STR0025 "Error indeterminado"
	#define STR0026 "Concluyo con exito la transmision del Protheus al Totvs Services SPED."
	#define STR0027 "Verifique si las facturas se autorizaron en SEFAZ, utilizando la rutina 'Monitor'. Antes de imprimir la DANFe."
	#define STR0028 "Se transmitio(eron)"
	#define STR0029 " factura(s) en "
	#define STR0030 "Hubo error durante la transmision al Totvs Services SPED."
	#define STR0031 "1-Produccion"
	#define STR0032 "2-Homologacion"
	#define STR0033 "1-Normal"
	#define STR0034 "2-Contingencia"
	#define STR0035 "Entorno"
	#define STR0036 "Modalidad"
	#define STR0037 "Version"
	#define STR0038 "Esta rutina tiene como objetivo ayudarlo en la configuracion de la integracion del Protheus con el servicio Totvs Services SPED. "
	#define STR0039 "El primer paso es configurar la conexion del Protheus con el servicio."
	#define STR0040 "Concluyo con exito la configuracion de la integracion del Protheus al Totvs Services."
	#define STR0041 "Assistente de configuração da nota fiscal eletrônica"
	#define STR0042 "Informe la URL del servidor Totvs Services"
	#define STR0043 "Informe el nombre del archivo del certificado digital"
	#define STR0044 "Drive:"
	#define STR0045 "Archivos .PEM |*.PEM"
	#define STR0046 "Informe el nombre del archivo de la private key"
	#define STR0047 "Informe la contrasena del archivo digital"
	#define STR0048 "Archivo no encontrado"
	#define STR0049 "Fact"
	#define STR0050 "Protocolo"
	#define STR0051 "Recomendacion"
	#define STR0052 "Tiempo transcurrido"
	#define STR0053 "Tempo SEF"
	#define STR0054 "Mensajes"
	#define STR0055 "Rec.XML"
	#define STR0056 "Produccion"
	#define STR0057 "Homologacion"
	#define STR0058 "Normal"
	#define STR0059 "Contingencia"
	#define STR0060 "Lote"
	#define STR0061 "Fch.Lote"
	#define STR0062 "Hr.Lote"
	#define STR0063 "Recibo SEF"
	#define STR0064 "Cod.Env.Lote"
	#define STR0065 "Msj.Env.Lote"
	#define STR0066 "Cod.Ret.Lote"
	#define STR0067 "Msj.Ret.Lote"
	#define STR0068 "Cod.Ret.Fe"
	#define STR0069 "Msj.Ret.Fe"
	#define STR0070 "Intervalo en minutos"
	#define STR0071 "Tiempo de espera"
	#define STR0072 "Seleccione el certificado"
	#define STR0073 "Espere"
	#define STR0074 "Anulacion/inutilizacion de Fact Electronicas"
	#define STR0075 "Tipo de Fact Elec"
	#define STR0076 "1-Salida"
	#define STR0077 "2-Entrada"
	#define STR0078 "fact. autorizada"
	#define STR0079 "Fact. no transmitida"
	#define STR0080 "Fact. transmitida"
	#define STR0081 "Fact. no autorizada"
	#define STR0082 "Filtrar"
	#define STR0083 "2-Sin filtro"
	#define STR0084 "1-Autorizadas"
	#define STR0085 "Servidor SMTP"
	#define STR0086 "Login del e-mail"
	#define STR0087 "Contrasena"
	#define STR0088 "Autenticacion"
	#define STR0089 "Solicitada"
	#define STR0090 "Cuenta de e-mail"
	#define STR0091 " "
	#define STR0092 "El Servidor SMTP del Totvs Sped no se configuro. La configuracion actual es:"
	#define STR0093 "Servidor POP"
	#define STR0094 "El servidor POP del Totvs Sped no se configuro. La configuracion actual es:"
	#define STR0095 "Informe el tipo de certificado digital:"
	#define STR0096 "Formato apache(.pem)"
	#define STR0097 "Formato PFX(.pfx o .p12)"
	#define STR0098 "Archivos(.PFX)|*.PFX|Archivos(.P12)|*.P12"
	#define STR0099 "Estadisticas"
	#define STR0100 "Fecha inicial"
	#define STR0101 "Fecha final"
	#define STR0102 "Servicio"
	#define STR0103 "Codigo"
	#define STR0104 "Mensaje"
	#define STR0105 "Transacciones"
	#define STR0106 "No hay datos"
	#define STR0107 "Consulta Fact"
#else
	#ifdef ENGLISH
		#define STR0001 "NFe-SEFAZ Monitoring"
		#define STR0002 "Range"
		#define STR0003 "Time"
		#define STR0004 "Search"
		#define STR0005 "Config.Wiz."
		#define STR0006 "Parameters"
		#define STR0007 "SEFAZ Status"
		#define STR0008 "Transmission"
		#define STR0009 "Monitor"
		#define STR0010 "Invoice Series"
		#define STR0011 "Initial invoice"
		#define STR0012 "Final invoice"
		#define STR0013 "The purpose of this routine is to help in the process of transmitting electronic invoice for Totvs Services SPED. "
		#define STR0014 "Currently, Totvs Services SPED is working with the following configuration: "
		#define STR0015 "Environment: "
		#define STR0016 "Generation mode: "
		#define STR0017 "Layout version: "
		#define STR0018 "Electronic invoice transmission wizard"
		#define STR0019 "Attention"
		#define STR0020 "Follow the instructions carefully for configuring the electronic invoice."
		#define STR0021 "Run the service configuration module before using this option!"
		#define STR0022 "Preparing invoice: "
		#define STR0023 "Transmitting XML from invoice: "
		#define STR0024 "The following invoices were rejected. Check the 'Monitor' routine to view the causes."
		#define STR0025 "Unknown error"
		#define STR0026 "You finished transmission from Protheus to Totvs Services SPED successfully."
		#define STR0027 "Check whether invoices were authorized in SEFAZ by using the 'Monitor' routine before printing DANFe."
		#define STR0028 "Invoices "
		#define STR0029 " were transmitted in "
		#define STR0030 "Error when transmitting to Totvs Services SPED."
		#define STR0031 "1-Production"
		#define STR0032 "2-Homologation"
		#define STR0033 "1-Normal"
		#define STR0034 "2-Contingence"
		#define STR0035 "Environment"
		#define STR0036 "Mode"
		#define STR0037 "Version"
		#define STR0038 "The purpose of this routine is to help configuring integration between Protheus and Totvs Services SPED. "
		#define STR0039 "The first step is to configure Protheus connection to the service."
		#define STR0040 "You configured the integration of Protheus with Totvs Services successfully."
		#define STR0041 "Electronic invoice configuration wizard"
		#define STR0042 "Enter the URL of Totvs Services server."
		#define STR0043 "Enter digital certificate file name "
		#define STR0044 "Drive:"
		#define STR0045 ".PEM |*.PEM files"
		#define STR0046 "Enter private key file name"
		#define STR0047 "Enter the password for digital file."
		#define STR0048 "File not found"
		#define STR0049 "IN"
		#define STR0050 "Voucher"
		#define STR0051 "Recommendation"
		#define STR0052 "Elapsed time"
		#define STR0053 "SEF Time"
		#define STR0054 "Messages"
		#define STR0055 "XML Rec."
		#define STR0056 "Production"
		#define STR0057 "Homologation"
		#define STR0058 "Normal"
		#define STR0059 "Contingence"
		#define STR0060 "Lot"
		#define STR0061 "Lot Dt."
		#define STR0062 "Lot Time"
		#define STR0063 "SEF Receipt"
		#define STR0064 "Lot Send.Cod."
		#define STR0065 "Lot Send.Msg."
		#define STR0066 "Lot With.Cod."
		#define STR0067 "Lot With.Msg."
		#define STR0068 "NFe With.Cod."
		#define STR0069 "NFe With.Msg."
		#define STR0070 "Interval in minutes"
		#define STR0071 "Lead time"
		#define STR0072 "Select certificate"
		#define STR0073 "Wait"
		#define STR0074 "Cancellation/Inutilization of NFe"
		#define STR0075 "NFe type"
		#define STR0076 "1-Outflow"
		#define STR0077 "2-Inflow"
		#define STR0078 "Invoice authorized"
		#define STR0079 "Invoice not transmitted"
		#define STR0080 "Invoice transmitted"
		#define STR0081 "Invoice not authorized"
		#define STR0082 "Filter"
		#define STR0083 "2-Without filter"
		#define STR0084 "1-Authorized"
		#define STR0085 "SMTP server"
		#define STR0086 "E-mail's login"
		#define STR0087 "Password"
		#define STR0088 "Authentication"
		#define STR0089 "Required"
		#define STR0090 "E-mail account"
		#define STR0091 " "
		#define STR0092 "Totvs Sped's SMTP server not configured. Current configuration: "
		#define STR0093 "POP server"
		#define STR0094 "Totvs Sped's POP server not configured. Current configuration: "
		#define STR0095 "Enter kind of digital certificate:"
		#define STR0096 "Apache format (.pem)"
		#define STR0097 "PFX format (.pfx or .p12)"
		#define STR0098 "(.PFX) files  |*.PFX|(.P12) files  |*.P12"
		#define STR0099 "Statistics"
		#define STR0100 "Initial date"
		#define STR0101 "Final date"
		#define STR0102 "Service"
		#define STR0103 "Code"
		#define STR0104 "Message"
		#define STR0105 "Transactions"
		#define STR0106 "No data available"
		#define STR0107 "Query invoice"
	#else
		#define STR0001 "Monitoramento da NFe-SEFAZ"
		#define STR0002 "Faixa"
		#define STR0003 "Tempo"
		#define STR0004 "Pesquisar"
		#define STR0005 "Wiz.Config."
		#define STR0006 "Parâmetros"
		#define STR0007 "Status SEFAZ"
		#define STR0008 "Transmissão"
		#define STR0009 "Monitor"
		#define STR0010 "Serie da nota fiscal"
		#define STR0011 "Nota fiscal inicial"
		#define STR0012 "Nota fiscal final"
		#define STR0013 "Esta rotina tem como objetivo auxilia-lo na transmissão da nota fiscal eletrônica para o serviço Totvs Services SPED. "
		#define STR0014 "Neste momento o Totvs Services SPED, está operando com a seguinte configuração: "
		#define STR0015 "Ambiente: "
		#define STR0016 "Modalidade de emissão: "
		#define STR0017 "Versão do layout: "
		#define STR0018 "Assistente de transmissão da nota fiscal eletrônica"
		#define STR0019 "Atenção"
		#define STR0020 "Siga atentamente os passos para a configuração da nota fiscal eletrônica."
		#define STR0021 "Execute o módulo de configuração do serviço, antes de utilizar esta opção!!!"
		#define STR0022 "Preparando nota: "
		#define STR0023 "Transmitindo XML da nota: "
		#define STR0024 "As notas abaixo foram recusadas, verifique a rotina 'Monitor' para saber os motivos."
		#define STR0025 "Erro indeterminado"
		#define STR0026 "Você concluíu com sucesso a transmissão do Protheus para o Totvs Services SPED."
		#define STR0027 "Verifique se as notas foram autorizadas na SEFAZ, utilizando a rotina 'Monitor'. Antes de imprimir a DANFe."
		#define STR0028 "Foram transmitidas "
		#define STR0029 " nota(s) em "
		#define STR0030 "Houve erro durante a transmissão para o Totvs Services SPED."
		#define STR0031 "1-Produção"
		#define STR0032 "2-Homologação"
		#define STR0033 "1-Normal"
		#define STR0034 "2-Contingência"
		#define STR0035 "Ambiente"
		#define STR0036 "Modalidade"
		#define STR0037 "Versão"
		#define STR0038 "Esta rotina tem como objetivo ajuda-lo na configuração da integração com o Protheus com o serviço Totvs Services SPED. "
		#define STR0039 "O primeiro passo é configurar a conexão do Protheus com o serviço."
		#define STR0040 "Você concluíu com sucesso a configuração da integração do Protheus para o Totvs Services."
		#define STR0041 "Assistente de configuração da nota fiscal eletrônica"
		#define STR0042 "Informe a URL do servidor Totvs Services"
		#define STR0043 "Informe o nome do arquivo do certificado digital"
		#define STR0044 "Drive:"
		#define STR0045 "Arquivos .PEM |*.PEM"
		#define STR0046 "Informe o nome do arquivo da private key"
		#define STR0047 "Informe senha do arquivo digital"
		#define STR0048 "Arquivo não encontrado"
		#define STR0049 "NF"
		#define STR0050 "Protocolo"
		#define STR0051 "Recomendação"
		#define STR0052 "Tempo decorrido"
		#define STR0053 "Tempo SEF"
		#define STR0054 "Mensagens"
		#define STR0055 "Rec.XML"
		#define STR0056 "Produção"
		#define STR0057 "Homologação"
		#define STR0058 "Normal"
		#define STR0059 "Contingência"
		#define STR0060 "Lote"
		#define STR0061 "Dt.Lote"
		#define STR0062 "Hr.Lote"
		#define STR0063 "Recibo SEF"
		#define STR0064 "Cod.Env.Lote"
		#define STR0065 "Msg.Env.Lote"
		#define STR0066 "Cod.Ret.Lote"
		#define STR0067 "Msg.Ret.Lote"
		#define STR0068 "Cod.Ret.NFe"
		#define STR0069 "Msg.Ret.NFe"
		#define STR0070 "Intervalo em minutos"
		#define STR0071 "Tempo de espera"
		#define STR0072 "Selecione o certificado"
		#define STR0073 "Aguarde"
		#define STR0074 "Cancelamento/inutilização de NFe's"
		#define STR0075 "Tipo de NFe"
		#define STR0076 "1-Saída"
		#define STR0077 "2-Entrada"
		#define STR0078 "NF autorizada"
		#define STR0079 "NF não transmitida"
		#define STR0080 "NF transmitida"
		#define STR0081 "NF não autorizada"
		#define STR0082 "Filtra"
		#define STR0083 "2-Sem filtro"
		#define STR0084 "1-Autorizadas"
		#define STR0085 "Servidor SMTP"
		#define STR0086 "Login do e-mail"
		#define STR0087 "Senha"
		#define STR0088 "Autenticação"
		#define STR0089 "Requerida"
		#define STR0090 "Conta de e-mail"
		#define STR0091 ""
		#define STR0092 "O Servidor SMTP do Totvs Sped não foi configurado. A configuração atual é:"
		#define STR0093 "Servidor POP"
		#define STR0094 "O servidor POP do Totvs Sped não foi configurado. A configuração atual é:"
		#define STR0095 "Informe o tipo de certificado digital:"
		#define STR0096 "Formato apache(.pem)"
		#define STR0097 "Formato PFX(.pfx ou .p12)"
		#define STR0098 "Arquivos(.PFX)|*.PFX|Arquivos(.P12)|*.P12"
		#define STR0099 "Estatísticas"
		#define STR0100 "Data inicial"
		#define STR0101 "Data final"
		#define STR0102 "Serviço"
		#define STR0103 "Código"
		#define STR0104 "Mensagem"
		#define STR0105 "Transações"
		#define STR0106 "Não há dados"
		#define STR0107 "Consulta NF"
	#endif
#endif
